openapi: 3.0.0
info:
  title: Til International Integration API
  description: "This is the documentation for integration with third-party systems\
    \ of Til International customers, for the purpose of sharing data from the Til\
    \ system with the customer's management system.\n\n# General:\n1.  The URL prefix\
    \ for all end  points is - **https://nlb.srv.tiltests.co.il/api**\n2.  Access\
    \ is possible via HTTPS only.\n3.  All requests must be accessed via HTTP BASIC\
    \ AUTO with the details provided to you by Til International.\n\n# API CALLS:\n\
    **Standard Requests:**\n1.  ***Register Candidate*** - This is a request to register\
    \ a new Candidate in the system, this request will open a new candidate in the\
    \ Til system and return the candidate key, the candidate key that will be provided\
    \ will be required in order to produce the examinee's results.\n2. This request\
    \ must be accompanied by a callback so that we can update you in the stages of\
    \ the diagnostic process .\n3.  ***Get Candidate Report*** - This request will\
    \ return the candidate's results. In order to receive the report, the candidate's\
    \ key must be provided as was received when opening a new candidate. The results\
    \ will be received as a base64 string format and the user need to convert it to\
    \ a PDF file.\n\n**Utility Requests:**\n1.  ***Delete Candidate*** - This is a\
    \ request to delete information about candidates from the Til system, this request\
    \ must be accompanied by the candidate's key as was received when registering\
    \ the candidate. Please note, it is possible to delete examinees only before the\
    \ exam not during.\n2.  ***Get Organization Routes*** - This request will return\
    \ all routes associated with the organization and available for examination.\n\
    3.  ***Get Sub Organizations*** - This request will return all sub organizations\
    \ associated with the organization.\n4.  ***Update Candidate Details*** - This\
    \ request will allow you to update the candidate's details if necessary, such\
    \ as - first name, ID number, extra time, etc .\n5.  ***Get Status*** – This request\
    \ will return the current status of the candidate. Also, after the status is updated,\
    \ the response to this request will be returned to the Callback provided when\
    \ registering the candidate in the system. Options - ‘NOT STARTED’, ‘STARTED’,\
    \ ‘COMPLETED’, ‘PAUSE’, ‘EXPIRED’.\n6.  ***Update Status*** – This request allows\
    \ to insert or remove the candidate from   'PAUSE' status\n    7.  ***Get Available\
    \ Flex Fields*** - This request returns the list of available flexible candidate\
    \ fields defined for the client's organization."
  termsOfService: https://tilint.com/
  contact:
    email: til.support@tilint.com
  version: 1.1.4
externalDocs:
  description: Find out more about Til International
  url: https://tilint.com/
servers:
- url: https://nlb.srv.tiltests.co.il/api
  description: provided to you by Til International.
security:
- basicAuth: []
tags:
- name: Standard Requests
- name: Utility Requests
paths:
  /registerCandidate:
    post:
      tags:
      - Standard Requests
      summary: Registerer a new candidate in the Til system
      description: 'Request to register a new candidate, after sending the request,
        a  unique key code will be received for the candidate. <br> The candidate
        key allows for additional actions on the candidate, such as, producing a report
        and updating details.<br> These are the required fields - first name, last
        name, gender, ID number, route, sub organization (if applicable).<br> After
        the status is updated, the response to this request will be returned to the
        Callback provided when registering the candidate in the system.<br> **Options**
        - ‘NOT STARTED’, ‘STARTED’, ‘COMPLETED’, ‘PAUSE’, ‘EXPIRED’. <br> Creation
        of a new candidate is valid for 30 days from the date of creation, after which
        the status of the candidate will change to ''EXPIRED'' and a new examination
        must be opened '
      operationId: registerCandidate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/registerCandidate_body'
            example:
              routeID: 1234
              idNumber: 123456789
              gender: 1
              firstName: John
              lastName: doe
              language: ENGLISH
              email: test@test.com
              phone: +1212-965-1698
              extraTime: 0
              callbackUrl: https://tilint.com/
              callbackUsername: user_name
              callbackPassword: password
              testType: 1
              flexField1Id: 0
              flexField1Value: string
              flexField2Id: 0
              flexField2Value: string
              flexField3Id: 0
              flexField3Value: string
              flexField4Id: 0
              flexField4Value: string
              flexField5Id: 0
              flexField5Value: string
      responses:
        '200':
          description: Candidate created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        '401':
          description: Authentication information is missing or invalid
          headers:
            WWW_Authenticate:
              style: simple
              explode: false
              schema:
                type: string
        '405':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
              example:
                result: error
                resultCode: 405
                message: Invalid request, missing first name
        '406':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
              example:
                result: error
                resultCode: 406
                message: Invalid input - ID value is not in the correct format
  /updateCandidateDetails:
    post:
      tags:
      - Utility Requests
      summary: Update candidate details
      description: "The details of the candidate can be updated at any time in the\
        \ Til system, for this purpose it is required to provide the unique key received\
        \ when registering the candidate.<br>\nThe rest of the fields are optional\
        \ fields if needed to update.<br>\nIf the candidate is **before** an examination,\
        \ all the fields can be changed.<br> \nWhen a candidate is doing an examination\
        \ it is not possible to change the route.<br>\nFor the candidate **after**\
        \ the exam, these values cannot be changed - route, extra time, exam language,\
        \ homeCandidate, testType.<br>\nThe parameter **testType** cannot be changed\
        \ when the exam status is **COMPLETED**.\n"
      operationId: updateCandidate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateCandidateDetails_body'
            example:
              candidateNumber: 3-365863
              routeID: 1234
              idNumber: 123456789
              gender: 1
              firstName: John
              extraTime: 25
              testType: 1
      responses:
        '200':
          description: Candidate updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
              example:
                candidateNumber: 3-365863
                result: success
                resultCode: 200
                message: Candidate updated
        '401':
          description: Authentication information is missing or invalid
          headers:
            WWW_Authenticate:
              style: simple
              explode: false
              schema:
                type: string
        '405':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
              example:
                result: error
                resultCode: 405
                message: Invalid request, missing first name
        '406':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
              example:
                result: error
                resultCode: 406
                message: Invalid input - ID value is not in the correct format
        '422':
          description: testType cannot be changed when the exam status is COMPLETED
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
              example:
                result: error
                resultCode: 422
                message: testType cannot be changed when the exam status is COMPLETED
  /getOrganizationRoutes/{organizationID}:
    get:
      tags:
      - Utility Requests
      summary: Returns list of available routes
      description: The request returns a list of routes associated with the organization,
        the 'organization id' value will be provided by Til International.
      operationId: getRoutes
      parameters:
      - name: organizationID
        in: path
        description: The organization number in 'TIL' system.
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: '150'
      responses:
        '200':
          description: Routes successfully produced
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_2'
              example:
                organizationID: 150
                routes:
                - routeID: 1234
                  routeName: route 1
                  reportTypes:
                  - reportID: 632
                    reportName: Golmi
                  - reportID: 633
                    reportName: Parshani
                  languages:
                  - languageName: HEBREW
                    languageID: 1
                  - languageName: ARABIC
                    languageID: 2
                  - languageName: ENGLISH
                - routeID: 12345
                  routeName: route 2
                  reportTypes:
                  - reportID: 632
                    reportName: Golmi
                  - reportID: 633
                    reportName: Parshani
                  languages:
                  - languageName: HEBREW
                    languageID: 1
                  - languageName: FRENCH
                    languageID: 6
                result: success
                resultCode: 200
                message: Routes successfully produced
        '401':
          description: Authentication information is missing or invalid
          headers:
            WWW_Authenticate:
              style: simple
              explode: false
              schema:
                type: string
        '404':
          description: Organization not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
              example:
                result: error
                resultCode: 404
                message: Organization not found
        '405':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
              example:
                result: error
                resultCode: 405
                message: Invalid request
  /getAvailableReportsByRoute/{routeNumber}:
    get:
      tags:
        - Reports
      summary: Get available reports by route
      description: |
        Returns the list of available report types for the given route.
      parameters:
        - in: path
          name: routeNumber
          required: true
          schema:
            type: integer
            example: 12
          description: The route number for which to retrieve the available reports.
      responses:
        '200':
          description: List of available reports for the route
          content:
            application/json:
              schema:
                type: object
                properties:
                  routeNumber:
                    type: integer
                    example: 12
                  reports:
                    type: array
                    items:
                      type: object
                      properties:
                        reportId:
                          type: integer
                          example: 1
                        reportName:
                          type: string
                          example: פרשני
              examples:
                success:
                  value:
                    routeNumber: 12
                    reports:
                      - reportId: 0
                        reportName: גולמי
                      - reportId: 1
                        reportName: פרשני
                      - reportId: 2
                        reportName: דוח פרשני מקוצר
                      - reportId: 8
                        reportName: דוח פרשני מותאם
                      - reportId: 9
                        reportName: דוח נציגים מקוצר
        '400':
          description: Invalid route number supplied
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid route number
        '404':
          description: Route not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Route not found
  /getCandidateReport/{candidateNumber}/{reportID}:
    get:
      tags:
      - Standard Requests
      summary: Return candidte report
      description: "The request returns a response object containing a pdf report\
        \ for the candidate.<br> A valid report will only be available once the candidate\
        \ has completed the test.<br> If the candidate has **not** started the test\
        \ the pdf report value will be a null value.<br>\n  The different report type\
        \ IDs can be obtained via getRoutes request."
      operationId: getCandidateReport
      parameters:
      - name: candidateNumber
        in: path
        description: The candidate key generated on candidate registration
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: 3-1234567
      - name: reportID
        in: path
        description: The ID of report you would like to receive. 
          0 - (גולמי), 
          1 - (פרשני), 
          2 - (דוח פרשני מקוצר), 
          8 - (דוח פרשני מותאם), 
          9 - (דוח נציגים מקוצר)
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          example: 3
      responses:
        '200':
          description: Report successfully produced
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_3'
              example:
                candidateNumber: 3-365863
                startTimeStamp: 27/02/2021
                pdfReport: pdf in base64 format
                status: COMPLETED
                result: success
                resultCode: 200
                message: Report successfully produced
        '201':
          description: No report
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_3'
              example:
                candidateNumber: 3-365863
                status: NOT STARTED
                result: success
                resultCode: 201
                message: No report can be produced for this candidate
        '401':
          description: Authentication information is missing or invalid
          headers:
            WWW_Authenticate:
              style: simple
              explode: false
              schema:
                type: string
        '404':
          description: Candidate not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
              example:
                result: error
                resultCode: 404
                message: Candidate not found
        '405':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
              example:
                result: error
                resultCode: 405
                message: Invalid request
        '422':
          description: The report template is not defined for this route
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
              example:
                result: error
                resultCode: 422
                message: The report template not defined to this route
  /getStatus/{candidateNumber}:
    get:
      tags:
      - Utility Requests
      summary: Return candidte status
      description: This request will return the current status of the candidate. Also,
        after the status is updated, the response to this request will be returned
        to the Callback provided when registering the candidate in the system. Options
        - ‘NOT STARTED’, ‘STARTED’, ‘COMPLETED’, ‘PAUSE’, ‘EXPIRED’.
      operationId: getStatus
      parameters:
      - name: candidateNumber
        in: path
        description: The candidate key generated on candidate registration
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: 3-1234567
      responses:
        '200':
          description: Successful request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_4'
              example:
                candidateNumber: 3-1234567
                startTimeStamp: 27/02/2021
                status: COMPLETED
                result: success
                resultCode: 200
                message: Successful request
        '401':
          description: Authentication information is missing or invalid
          headers:
            WWW_Authenticate:
              style: simple
              explode: false
              schema:
                type: string
        '404':
          description: Candidate not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
              example:
                result: error
                resultCode: 404
                message: Candidate not found
        '405':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
              example:
                result: error
                resultCode: 405
                message: Invalid request
  /getSubOrganizations/{organizationID}:
    get:
      tags:
      - Utility Requests
      summary: Returns a list of existing sub-organizations
      description: This request will return a list of existing sub-organizations.
      operationId: getSubOrganizations
      parameters:
      - name: organizationID
        in: path
        description: The organization number in 'TIL' system.
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          example: 150
      responses:
        '200':
          description: Successful request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_5'
              example:
                result: success
                resultCode: 200
                message: Successful request
        '401':
          description: Authentication information is missing or invalid
          headers:
            WWW_Authenticate:
              style: simple
              explode: false
              schema:
                type: string
        '404':
          description: Organization not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
              example:
                result: error
                resultCode: 404
                message: Organization not found
        '405':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
              example:
                result: error
                resultCode: 405
                message: Invalid request
  /updateStatus/{candidateNumber}:
    get:
      tags:
      - Utility Requests
      summary: Update candidte status
      description: This request allows to insert or remove the candidate from PAUSE
        status
      operationId: updateStatus
      parameters:
      - name: candidateNumber
        in: path
        description: The candidate key generated on candidate registration
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: 3-1234567
      responses:
        '200':
          description: Successful request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_5'
              example:
                candidateNumber: 3-1234567
                startTimeStamp: 27/02/2021
                status: COMPLETED
                result: success
                resultCode: 200
                message: Status update
        '401':
          description: Authentication information is missing or invalid
          headers:
            WWW_Authenticate:
              style: simple
              explode: false
              schema:
                type: string
        '404':
          description: Candidate not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
              example:
                result: error
                resultCode: 404
                message: Candidate not found
        '405':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
              example:
                result: error
                resultCode: 405
                message: Invalid request
  /deleteCandidate/{candidateNumber}:
    delete:
      tags:
      - Utility Requests
      summary: Delete purchase order by ID
      description: This request allows deletion of an examinee from the Til system.  The
        candidate key must be attached to the request.<br> Please note, deletion is
        possible for candidates who are before the exam only.
      parameters:
      - name: candidateNumber
        in: path
        description: The candidate key generated on candidate registration
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        '200':
          description: Candidate deleted
          content:
            apllication/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_6'
              example:
                candidateNumber: 3-1234567
                result: success
                resultCode: 200
                message: Candidate deleted
        '401':
          description: Authentication information is missing or invalid
          headers:
            WWW_Authenticate:
              style: simple
              explode: false
              schema:
                type: string
        '402':
          description: Candidate not deleted
          content:
            apllication/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
              example:
                candidateNumber: 3-1234567
                result: error
                resultCode: 402
                message: A candidate who started the exam cannot be deleted
        '404':
          description: Candidate not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
              example:
                result: error
                resultCode: 404
                message: Candidate not found
        '405':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
              example:
                result: error
                resultCode: 405
                message: Invalid request
  /GetCandidateData/{candidateNumber}:
    get:
      tags:
      - Utility Requests
      summary: Get candidate data
      description: The request deletes tests from candidate's route. The test can
        be deleted only if it is in (לפני בחינה) testStatus. The identifier and testStatus
        are obtained through /getCandidateData request.
      parameters:
      - name: candidateNumber
        in: path
        description: The candidate key generated on candidate registration
        required: true
        schema:
          type: string
          example: 57-1004768
      responses:
        '200':
          description: Candidate data successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetCandidateData'
              example:
                candidateRouteId: 149051
                subOrganizationId: null
                subOrganizationName: null
                idNumber: '131020240'
                gender: 2
                firstName: ksu
                lastName: test
                language: Hebrew
                email: null
                phone: null
                createdBy: ksu@tilint.com
                extraTime: 0
                route:
                  routeName: 'שירות לקוחות טלפוני מקוצר - ישראכארט '
                  routeID: 236
                status: לפני בחינה
                daysUntilExpired: 6
                emailLanguage: Hebrew
                jobTitle: null
                examType: בחינה בארגון
                invitationDateFrom: '2024-10-13T10:50:01.7366667'
                invitationDateUntil: '2024-10-20T10:50:01.7366667'
                candidateExams:
                - examName: סדרות מספריות א
                  examNumber: '101'
                  testStatus: לפני בחינה
                  examExtraTime: 0
                  examLanguage: Hebrew
                  testOrder: 1
                  identifier: '1483738'
                emails: []
                flexField1Value: ''
                flexField2Value: ''
                flexField3Value: ''
                flexField4Value: ''
                flexField5Value: ''
                result: success
                resultCode: 200
                message: null
        '401':
          description: Authentication information is missing or invalid
        '404':
          description: Candidate not found
        '405':
          description: Invalid request
  /DeleteTestsFromCandidateRoute:
    post:
      tags:
      - Utility Requests
      summary: Delete an exam from candidate's route
      description: This request deletes a test from the candidate's route. The identifiers
        are received through the GetCandidateData function. Please note the deletion
        is possible only for tests that haven't been started yet
      operationId: deleteTestsFromCandidateRoute
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/deleteTestsFromCandidateRoute_body'
            example:
              candidateNumber: 57-1004768
              identifiers:
              - 1483739
      responses:
        '200':
          description: Exams deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
              example:
                entityId: 0
                isSucceeded: true
                continuationActionData: null
                result: success
                resultCode: 200
                message: null
        '401':
          description: Authentication information is missing or invalid
        '404':
          description: Candidate or exam not found
        '405':
          description: Invalid request
  /GetCandidateImage/{candidateNumber}:
    get:
      tags:
      - Utility Requests
      summary: Get candidate image
      description: 'The request allows to retrieve an URL to the candidate''s image.
        Candidate''s image exists only when examType is (בחינה מהבית + Agent), examType
        is obtained through /getCandidateData request. '
      operationId: getCandidateImage
      parameters:
      - name: candidateNumber
        in: path
        description: The candidate key generated on candidate registration
        required: true
        schema:
          type: string
          example: 57-1234567
      responses:
        '200':
          description: Candidate image link successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetCandidateImageResponse'
              example:
                preSignedUrl: https://il-rekognition-intput-prod.s3.il-central-1.amazonaws.com/...
                fileName: 125678/125678_index.jpeg
                result: success
                resultCode: 200
                message: null
        '401':
          description: Authentication information is missing or invalid
        '404':
          description: Candidate or image not found
        '405':
          description: Invalid request
  /GetAvailableRouteTests/{OrganizationId}/{RouteId}:
    get:
      tags:
      - Utility Requests
      summary: Get available route tests
      description: The request returns all the tests available at the given route.
        Requires “organizationId” and “routeId” that can be obtained through /getOrganizationRoutes.
      operationId: getAvailableRouteTests
      parameters:
      - name: OrganizationId
        in: path
        description: The organization ID for which available tests need to be fetched
        required: true
        schema:
          type: integer
          example: 57
      - name: RouteId
        in: path
        description: The route ID for which available tests need to be fetched
        required: true
        schema:
          type: integer
          example: 236
      responses:
        '200':
          description: List of available tests for the route
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAvailableRouteTestsResponse'
              example:
                routeName: 'שירות לקוחות טלפוני מקוצר - ישראכארט '
                routeId: 236
                tests:
                - name: בעיות כמותיות א'
                  examNumber: '100'
                  identifier: exam-1
                - name: סדרות מספריות א
                  examNumber: '101'
                  identifier: exam-10
                totalCount: 37
                result: success
                resultCode: 200
                message: null
        '401':
          description: Authentication information is missing or invalid
        '404':
          description: Route or organization not found
        '405':
          description: Invalid request
  /sendMail:
    post:
      tags:
      - Utility Requests
      summary: 'The request allows to send an invitation and reminder email to the
        candidate. Requires email address in candidate''s details. The parameters
        for sending are “candidateNumber” and “mailType”. The last parameter is an
        integer with values: 4 - for invitation mail, 5 for reminder mail. /getCandidateData
        shows the emails that has been sent in the “emails” value.'
      operationId: sendMail
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/sendMail_body'
            examples:
              invitationMail:
                value:
                  candidateNumber: 57-1004767
                  mailType: 4
      responses:
        '200':
          description: Mail sent successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
              example:
                entityId: 0
                isSucceeded: true
                continuationActionData: null
                result: success
                resultCode: 200
                message: null
        '401':
          description: Authentication information is missing or invalid
        '404':
          description: Candidate not found
        '405':
          description: Invalid request
  /AddCandidateTests:
    post:
      tags:
      - Utility Requests
      summary: Add exams to candidate's route
      description: The request allows to add a test to the candidate's route by sending
        “candidateNumber” and “identifiers” parameters. “identifiers” can be obtained
        with /getAvailableRouteTests call.
      operationId: addCandidateTests
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/addCandidateTests_body'
            example:
              candidateNumber: 57-1004790
              identifiers:
              - exam-214
              - inclusiveTest-27
      responses:
        '200':
          description: Exams added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
              example:
                entityId: 0
                isSucceeded: true
                continuationActionData: null
                result: success
                resultCode: 200
                message: null
        '401':
          description: Authentication information is missing or invalid
        '404':
          description: Candidate not found
        '405':
          description: Invalid request
  /GetAvailableFlexFields:
    get:
      tags:
      - Utility Requests
      summary: Returns list of available flexible fields
      description: Returns the list of flexible candidate detail fields defined for
        the client's organization. These field IDs can be used in the registerCandidate
        request via flexField1Id-flexField5Id together with their matching values.
      operationId: getAvailableFlexFields
      responses:
        '200':
          description: Flexible fields successfully produced
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAvailableFlexFieldsResponse'
              example:
                flexFields:
                - id: 17
                  displayName: birth date
                  flexFieldOptions: []
                  required: true
                totalCount: 1
                result: success
                resultCode: 200
                message: null
        '401':
          description: Authentication information is missing or invalid
          headers:
            WWW_Authenticate:
              style: simple
              explode: false
              schema:
                type: string
        '405':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
              example:
                result: error
                resultCode: 405
                message: Invalid request
components:
  schemas:
    Routs:
      type: object
      properties:
        organizationID:
          type: integer
          description: The organization id that supply from Til International while
            receiving API access information
          format: integer
          example: 3
        routes:
          type: array
          items:
            $ref: '#/components/schemas/Routs_routes'
    Delete:
      type: object
      properties:
        candidateNumber:
          type: string
          description: The unique candidate key.
          format: string
          example: 3-365863
    Register:
      type: object
      properties:
        candidateNumber:
          type: string
          description: The unique candidate key.
          format: string
          example: 3-365863
        testExpirationDate:
          type: string
          description: An ISO 8601 formatted timestamp of expiration date for answering
            the test.
          example: 27/02/2021
        url:
          type: string
          description: The exam  URL.
          example: tilint.com
        registrationUrl:
          type: string
          description: Registration link for the exam from home
          example: https://www.tor4you.co.il/tilst.asp?siteid=4791&sid=A4EAE95428D76639
    Update:
      type: object
      properties:
        candidateNumber:
          type: string
          description: The unique candidate key.
          format: string
          example: 3-365863
    GetStatus:
      type: object
      properties:
        candidateNumber:
          type: string
          description: The unique candidate key.
          format: string
          example: 3-365863
        timestampStart:
          type: string
          description: an ISO 8601 formatted timestamp of when the candidate started
            the test
        status:
          type: string
          description: Status in which the candidate is – Options - ‘NOT STARTED’,
            ‘STARTED’, ‘COMPLETED’, ‘PAUSE’, ‘EXPIRED’
    ApiResponse:
      type: object
      properties:
        result:
          type: string
          description: “success” or “error”.
          example: success
          enum:
          - success
          - error
        result_code:
          type: integer
          description: Numeric code for support purposes.
        message:
          type: string
          description: Human readable description of result.
    GetReport:
      type: object
      properties:
        candidateNumber:
          type: string
          description: The candidate key generated on candidate registration
        startTimestamp:
          type: string
          description: an ISO 8601 formatted timestamp of when the candidate started
            the test
        pdfReport:
          type: string
          description: A pdf report containing the candidate's result
          format: base64
        status:
          type: string
          description: Status in which the candidate is – Options - ‘NOT STARTED’,
            ‘STARTED’, ‘COMPLETED’, ‘PAUSE’, ‘EXPIRED’
    registerCandidate_body:
      required:
      - callbackPassword
      - callbackUrl
      - callbackUsername
      - firstName
      - gender
      - idNumber
      - language
      - lastName
      - routeID
      type: object
      properties:
        organization:
          type: integer
          description: The organization number in the 'TIL' system. This is a required
            field if the user has permission to more than one organization.
        subOrganization:
          type: integer
          description: The list of sub-organizations can be obtained from 'getSubOrganizations'
            request
        routeID:
          type: string
          description: static key provided by Til International to accompany each
            request – You can get all the keys belonging to the organization through
            getOrganizationRoutes API request
          format: string
        idNumber:
          type: string
          description: candidate id
        gender:
          type: integer
          description: candidate gender – “1” for male or “2” for female
          enum:
          - 1
          - 2
        firstName:
          type: string
          description: candidate first name
        lastName:
          type: string
          description: candidate last name
        language:
          type: integer
          description: candidate test language - 1 for Hebrew, 2 for English, 3 for
            Arabic, 4 for French, 5 for Russian, 6 for Spanish
          enum:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
        email:
          type: string
          description: candidate email address – REQUIRED for routes with mail option
            like AI tracking routes
        phone:
          type: string
          description: candidate phone number
        extraTime:
          type: integer
          description: The extra time required for the candidate
          enum:
          - 0
          - 20
          - 25
          - 50
          - 75
          - 100
        callbackUrl:
          type: string
          description: HTTP URL to which candidate status are POSTed on test started
            or completion. JSON data will be POSTed to this url in the same format
            as the “getStatus” from this API
        callbackUsername:
          type: string
          description: HTTP Basic Auto username for callback
        callbackPassword:
          type: string
          description: HTTP Basic Auto password for callback
        homeCandidate:
          type: boolean
          description: If the candidate is examined from home Should be sent 'TRUE'
            value. the default value is 'FALSE'. If the candidate is set for examination
            from home you will receive a link to register for the exam. This link
            should be sent to the candidate in order to set a date for the exam.
        testType:
          type: integer
          description: "Exam type. Allowed values: 1 = בחינה בארגון, 3 = בחינה מהבית + אייג'נט."
          enum:
          - 1
          - 3
          example: 1
        flexField1Id:
          type: integer
          description: The ID of flexible field slot 1. Available IDs can be obtained
            from the GetAvailableFlexFields request.
        flexField1Value:
          type: string
          description: The value to assign to flexible field slot 1.
        flexField2Id:
          type: integer
          description: The ID of flexible field slot 2. Available IDs can be obtained
            from the GetAvailableFlexFields request.
        flexField2Value:
          type: string
          description: The value to assign to flexible field slot 2.
        flexField3Id:
          type: integer
          description: The ID of flexible field slot 3. Available IDs can be obtained
            from the GetAvailableFlexFields request.
        flexField3Value:
          type: string
          description: The value to assign to flexible field slot 3.
        flexField4Id:
          type: integer
          description: The ID of flexible field slot 4. Available IDs can be obtained
            from the GetAvailableFlexFields request.
        flexField4Value:
          type: string
          description: The value to assign to flexible field slot 4.
        flexField5Id:
          type: integer
          description: The ID of flexible field slot 5. Available IDs can be obtained
            from the GetAvailableFlexFields request.
        flexField5Value:
          type: string
          description: The value to assign to flexible field slot 5.
    inline_response_200:
      example:
        candidateNumber: 3-365863
        testExpirationDate: 02/27/2021
        url: tilint.com
        registrationUrl: https://www.tor4you.co.il/tilst.asp?siteid=4791&sid=A4EAE95428D76639
        result: success
        resultCode: 200
        message: Candidate created
      allOf:
      - $ref: '#/components/schemas/Register'
      - $ref: '#/components/schemas/ApiResponse'
    updateCandidateDetails_body:
      required:
      - candidateNumber
      type: object
      properties:
        candidateNumber:
          type: string
          description: The candidate key generated on candidate registration
        subOrganization:
          type: integer
          description: The list of sub-organizations can be obtained from 'getSubOrganizations'
            request
        routeID:
          type: string
          description: static key provided by Til International to accompany each
            request – You can get all the keys belonging to the organization through
            Get organization routes API request
          format: string
        idNumber:
          type: string
          description: candidate id
        gender:
          type: integer
          description: candidate gender – “1” for male or “2” for female
          enum:
          - 1
          - 2
        firstName:
          type: string
          description: candidate first name
        lastName:
          type: string
          description: candidate last name
        language:
          type: string
          description: candidate test language
          enum:
          - HEBREW
          - ARABIC
          - ENGLISH
          - RUSSIAN
          - SPANISH
          - FRENCH
        email:
          type: string
          description: candidate email address
        phone:
          type: string
          description: candidate phone number
        homeCandidate:
          type: boolean
          description: TRUE or FALSE
        extraTime:
          type: integer
          description: The extra time required for the candidate
          enum:
          - 0
          - 20
          - 25
          - 50
          - 75
          - 100
        testType:
          type: integer
          description: "Exam type. Allowed values: 1 = בחינה בארגון, 3 = בחינה מהבית + אייג'נט. This value cannot be changed when the exam status is COMPLETED."
          enum:
          - 1
          - 3
          example: 1
        invitationDateFrom:
          type: string
          description: date when candidate can start the exam. YYYY-MM-DD or YYYY-MM-DDTHH:MM:SS
            both formats are accepted
        invitationDateUntil:
          type: string
          description: date till when candidate can do the exam. YYYY-MM-DD or YYYY-MM-DDTHH:MM:SS
            both formats are accepted
    GetCandidateData:
      type: object
      properties:
        candidateRouteId:
          type: integer
        subOrganizationId:
          type: integer
          nullable: true
        subOrganizationName:
          type: string
          nullable: true
        idNumber:
          type: string
        gender:
          type: integer
        firstName:
          type: string
        lastName:
          type: string
        language:
          type: string
        email:
          type: string
          nullable: true
        phone:
          type: string
          nullable: true
        createdBy:
          type: string
        extraTime:
          type: integer
        route:
          $ref: '#/components/schemas/Routs_routes'
        status:
          type: string
        daysUntilExpired:
          type: integer
        emailLanguage:
          type: string
          nullable: true
        jobTitle:
          type: string
          nullable: true
        examType:
          type: string
        invitationDateFrom:
          type: string
          format: date-time
        invitationDateUntil:
          type: string
          format: date-time
        candidateExams:
          type: array
          items:
            $ref: '#/components/schemas/candidateExams'
        emails:
          type: array
          items:
            $ref: '#/components/schemas/Email'
        flexField1Value:
          type: string
        flexField2Value:
          type: string
        flexField3Value:
          type: string
        flexField4Value:
          type: string
        flexField5Value:
          type: string
        result:
          type: string
        resultCode:
          type: integer
        message:
          type: string
          nullable: true
    deleteTestsFromCandidateRoute_body:
      type: object
      properties:
        candidateNumber:
          type: string
          description: The candidate key generated on candidate registration
        identifiers:
          type: array
          items:
            type: integer
          description: List of exam identifiers to delete
    GetCandidateImageResponse:
      type: object
      properties:
        preSignedUrl:
          type: string
          description: URL to the candidate's image
        fileName:
          type: string
          description: Name of the image file
        result:
          type: string
          description: Operation result, e.g., success or error
        resultCode:
          type: integer
          description: Result code of the operation
        message:
          type: string
          nullable: true
          description: Additional message, if applicable
    candidateExams:
      type: array
      items:
        type: object
        properties:
          examName:
            type: string
            description: Name of the exam
          examNumber:
            type: string
            description: Unique identifier for the exam
          testStatus:
            type: string
            description: Status of the exam, can be (לפני בחינה), (במהלך בחינה), (לאחר בחינה)
          examExtraTime:
            type: integer
            description: Extra time allowed for the exam in minutes
          examLanguage:
            type: string
            description: Language of the exam
          testOrder:
            type: integer
            description: Order of the exam in the candidate's route
          identifier:
            type: string
            description: Unique identifier for the specific test instance
    GetAvailableRouteTestsResponse:
      type: object
      properties:
        routeName:
          type: string
          description: The name of the route
        routeId:
          type: integer
          description: The ID of the route
        tests:
          type: array
          items:
            $ref: '#/components/schemas/tests'
        totalCount:
          type: integer
          description: The total number of available tests
        result:
          type: string
          description: The result status
        resultCode:
          type: integer
          description: The result code
        message:
          type: string
          nullable: true
          description: An optional message
    tests:
      type: array
      items:
        type: object
        properties:
          name:
            type: string
            description: Name of the test
          examNumber:
            type: string
            description: Unique identifier for the test
          identifier:
            type: string
            description: Unique identifier for the specific instance of the test
    sendMail_body:
      type: object
      properties:
        candidateNumber:
          type: string
          description: The candidate key generated on candidate registration
        mailType:
          type: integer
          description: Type of mail to be sent (4 for invitation, 5 for reminder)
          enum:
          - 4
          - 5
      required:
      - candidateNumber
      - mailType
    addCandidateTests_body:
      type: object
      properties:
        candidateNumber:
          type: string
          description: The candidate key generated on candidate registration
        identifiers:
          type: array
          items:
            type: string
          description: List of exam identifiers to add to the candidate's route
    inline_response_200_1:
      allOf:
      - $ref: '#/components/schemas/Update'
      - $ref: '#/components/schemas/ApiResponse'
    inline_response_200_2:
      allOf:
      - $ref: '#/components/schemas/Routs'
      - $ref: '#/components/schemas/ApiResponse'
    inline_response_200_3:
      allOf:
      - $ref: '#/components/schemas/GetReport'
      - $ref: '#/components/schemas/ApiResponse'
    inline_response_200_4:
      allOf:
      - $ref: '#/components/schemas/GetStatus'
      - $ref: '#/components/schemas/ApiResponse'
    inline_response_200_5:
      allOf:
      - $ref: '#/components/schemas/ApiResponse'
    inline_response_200_6:
      allOf:
      - $ref: '#/components/schemas/Delete'
      - $ref: '#/components/schemas/ApiResponse'
    Routs_reportTypes:
      type: object
      properties:
        reportID:
          type: integer
        reportName:
          type: string
    Routs_languages:
      type: object
      properties:
        languageName:
          type: string
        languageID:
          type: integer
    Routs_routes:
      type: object
      properties:
        routeID:
          type: string
        routeName:
          type: string
        reportTypes:
          type: array
          items:
            $ref: '#/components/schemas/Routs_reportTypes'
        languages:
          type: array
          items:
            $ref: '#/components/schemas/Routs_languages'
    Email:
      type: object
      properties:
        date:
          type: string
          format: date
        typeID:
          type: integer
        typeName:
          type: string
    FlexFieldOption:
      type: object
      properties:
        id:
          type: integer
          description: The option identifier.
        displayName:
          type: string
          description: The option display name.
    FlexField:
      type: object
      properties:
        id:
          type: integer
          description: The flexible field identifier to be used in registerCandidate.
        displayName:
          type: string
          description: The flexible field display name.
        flexFieldOptions:
          type: array
          description: Available options for the flexible field, if applicable. Empty for free-text fields.
          items:
            $ref: '#/components/schemas/FlexFieldOption'
        required:
          type: boolean
          description: Indicates whether the field is required.
    GetAvailableFlexFields:
      type: object
      properties:
        flexFields:
          type: array
          items:
            $ref: '#/components/schemas/FlexField'
        totalCount:
          type: integer
          description: Total number of available flexible fields.
    GetAvailableFlexFieldsResponse:
      allOf:
      - $ref: '#/components/schemas/GetAvailableFlexFields'
      - $ref: '#/components/schemas/ApiResponse'
  responses:
    UnauthorizedError:
      description: Authentication information is missing or invalid
      headers:
        WWW_Authenticate:
          style: simple
          explode: false
          schema:
            type: string
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
